# Generated by Django 5.0.7 on 2024-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="is_counted",
            field=models.BooleanField(default=False),
        ),
    ]
