# Generated by Django 5.0.7 on 2024-08-22 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0002_codesubmission_is_counted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codesubmission",
            name="is_counted",
        ),
    ]
