# Generated by Django 5.0.7 on 2024-08-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_testcase"),
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaderboard",
            old_name="score",
            new_name="total_accepted",
        ),
        migrations.RemoveField(
            model_name="question",
            name="status",
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="latest_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submit.codesubmission",
            ),
        ),
    ]
