# Generated by Django 5.0.7 on 2024-08-23 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_rename_score_leaderboard_total_accepted_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Leaderboard",
        ),
    ]
