# Generated by Django 5.0.7 on 2024-08-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_delete_leaderboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="constraint_n",
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name="question",
            name="time_limit",
            field=models.FloatField(default=1.0),
        ),
    ]
