# Generated by Django 5.0.7 on 2024-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_question_constraint_n_question_time_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="constraint_n",
            field=models.TextField(),
        ),
    ]
