# Generated by Django 5.0.7 on 2024-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_question_constraint_n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(default="no description", max_length=2000),
        ),
        migrations.AlterField(
            model_name="question",
            name="example_input",
            field=models.TextField(default="no example", max_length=1000),
        ),
        migrations.AlterField(
            model_name="question",
            name="example_output",
            field=models.TextField(default="no example", max_length=1000),
        ),
    ]
